package util

// PRESENTLY LOCKED:
// Currently above variables MUST be locked.
// The program must take in a 1280x720 image and output a 3840x2160 mosaic
// Later I might make this more dynamic
const InputResolutionX = 1280
const InputResolutionY = 720
const SaveResolutionX = 3840
const SaveResolutionY = 2160
const SpriteType = "square"

// These are POSSIBLE resize resolutions given the above constraints
// If the resolutions become dynamic they can be generated by finding
// the greatest common divisor between the X and Y resolution of the save file
var ResizeResolutions = []int{120, 80, 60, 48, 40, 30, 24, 16, 15, 12}
