#pragma once

#include <string>

// Currently, below constants MUST be locked.
// The program must take in a 1280x720 image and output a 3840x2160 mosaic.
const int INPUT_RESOLUTION_X = 1280;
const int INPUT_RESOLUTION_Y = 720; 
const int SAVE_RESOLUTION_X = 3840;
const int SAVE_RESOLUTION_Y = 2160;

const std::string SPRITE_TYPE = "square";

// These are POSSIBLE resize resolutions given the above constraints
// If the resolutions become dynamic they can be generated by finding
// the greatest common divisor between the X and Y resolution of the save file
const int RESIZE_RESOLUTIONS[10] = {
    120,
    80,
    60,
    48,
    40,
    30,
    24,
    16,
    15,
    12,
};