[package]
name = "spritefi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]


[features]
default = ["console_error_panic_hook"]

[dependencies]
fixed = "1.27.0"
image = "0.25.0"
kdtree = "0.7.0"
kiddo = { version = "4.2.0", features = ["serialize"] }
serde = { version = "1.0.197", features = ["derive"] }
wasm-bindgen = "0.2.92"
postcard = { version = "1.0.0", features = ["alloc"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
