name: Go

on: [push]

jobs:
  build-mac:

    runs-on: macos-latest
    steps:
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download dependencies
        run: go mod download
      - name: Install vips
        run: brew install vips
      - name: Build Test
        run: |
          cd src/main
          go build
      - name: Custom Continuous Integration Tests
        run: |
          cd src/main
          go run main.go CI_testing

  build-linux:

    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download dependencies
        run: go mod download
      - name: Install vips
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev libwayland-client0 libwayland-dev libxkbcommon-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev
      - name: Custom Continuous Integration Tests
        run: |
          cd src/main
          go run main.go CI_testing


  build-windows:
    runs-on: windows-latest
    steps:
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download dependencies
        run: go mod download
      - name: Install libvips
        run: |
          curl -L -o vips.tar.gz https://github.com/libvips/build-win64-mxe/releases/download/v8.15.2/vips-dev-w32-web-8.15.2-static.zip
          tar xvf vips.tar.gz
          echo "$PWD/vips-8.12.1/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build Test
        run: |
          cd src/main
          go build
      - name: Custom Continuous Integration Tests
        run: |
          cd src/main
          go run main.go CI_testing