# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6' #is this correct? Your version is earlier...
        
    - name: Install libvips (for gopkg.in/h2non/bimg.v1)
      run: sudo apt-get update && sudo apt-get install -y libvips-dev

    - name: Install Wayland development files (for github.com/gen2brain/raylib-go/raylib)
      run: sudo apt-get update && sudo apt-get install -y libwayland-dev
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
