name: Go

on: [push]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download dependencies
        run: go mod download
      - name: Change Directory
        run: cd src
      - name: Build project
        run: go build ..