name: Go Continuous Integration
#from chatGPT
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: [1.21.6]
        arch: [arm64]
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensures history for all branches is fetched

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Set up environment
      run: |
        echo "GOOS=darwin" >> $GITHUB_ENV
        echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV

    - name: Check Go version
      run: go version

    - name: Get dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
